team_builder/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'email_confirmation/',
        views.email_confirmation_view,
        name='email_confirmation'
    ),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path(
        'token_confirmation/<str:token>/',
        views.token_confirmation,
        name='token_confirmation'
    ),
]

team_builder/notification_hub/urls.py
from django.urls import path

from . import views

app_name = 'notification_hub'

urlpatterns = [
    path('all/', views.notifications, name='notifications'),
    path(
        'deletion/<int:pk>',
        views.delete,
        name='delete'
    ),
    path(
        'deletion_view',
        views.deletion_view,
        name='deletion_view'
    ),
    path(
        'mark_read/<int:pk>/',
        views.mark_read,
        name='mark_read'
    ),
    path(
        'mark_unread/<int:pk>/',
        views.mark_unread,
        name='mark_unread'
    ),
    path(
        'unread',
        views.unread,
        name='unread'
    ),
    path(
        'read',
        views.read,
        name='read'
    ),
]

team_builder/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'

urlpatterns = [
    # Miscellaneous related paths
    path('', views.HomepageListView.as_view(), name='homepage'),
    path('login_router', views.login_router, name='login_router'),
    path('new_skill', views.new_skill, name='new_skill'),

    # Administrative related paths
    path('administrative', views.administrative, name='administrative'),
    path(
        'administrative/non_pending',
        views.administrative_non_pending,
        name='administrative_non_pending'
    ),
    path(
        'administrative/skill/<int:pk>/accept',
        views.skill_accept,
        name='skill_accept'
    ),
    path(
        'administrative/skill/<int:pk>/deny',
        views.skill_deny,
        name='skill_deny'
    ),

    # Applications related paths
    path('applications', views.applications, name='applications'),

    path('applications/accept/<int:position_pk>/<int:profile_pk>',
         views.applications_accept,
         name='applications_accept'),

    path('applications/reject/<int:position_pk>/<int:profile_pk>',
         views.applications_reject,
         name='applications_reject'),

    path('applications/request/<int:pk>',
         views.applications_request,
         name='applications_request'),

    path('applications/view/accepted',
         views.applications_view_accepted,
         name='applications_view_accepted'),

    path('applications/view/rejected',
         views.applications_view_rejected,
         name='applications_view_rejected'),

    # Profile related paths
    path('profile/edit/', views.profile_edit, name='edit'),
    path(
        'profile/edit/image/',
        views.profile_edit_image,
        name='profile_edit_image'
    ),
    path(
        'profile/view/<int:pk>/',
        views.profile_view,
        name='profile'
    ),

    # Project related paths
    path(
        'project/delete/<int:pk>',
        views.project_delete,
        name='project_delete'
    ),
    path(
        'project/delete_confirmation/<int:pk>',
        views.project_delete_confirmation,
        name='project_delete_confirmation'
    ),
    path('project/edit/<int:pk>', views.project_edit, name='project_edit'),
    path('project/new', views.project_new, name='project_new'),
    path('project/view/<int:pk>/', views.project_view, name='project'),
    path('project/view_all', views.project_view_all, name='project_view_all'),

    # Search related paths
    path('search', views.SearchListView.as_view(), name='search'),
    path(
        'search/skill/<str:skill>',
        views.SearchBySkillListView.as_view(),
        name='search_by_skill'
    ),
    path('search/your_skills',
         views.SearchYourSkillsView.as_view(),
         name='search_your_skills'
    ),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# django-notifications
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'),),
    path('accounts/', include('django.contrib.auth.urls'),),
    url('^inbox/notifications/',
        include(notifications.urls, namespace='notifications')
        ),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^notifications/', include('notification_hub.urls')),
    path('', include('profiles.urls'))
]

# Enable the Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

team_builder/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>{% block title_tag %}Team Builder {% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
        rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet'
        type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/global.css' %}">

  {#  Check to see if the user is logged in. If so grab their preferred stylesheet  #}
  {% if user.is_authenticated %}

    {#    Creates a stylesheet from user.color and renders it#}
    {% with 'css/'|add:user.color|add:'.css' as stylesheet %}
      <link rel="stylesheet" href="{% static stylesheet %}">
    {% endwith %}


  {% endif %}

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript"
          src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


</head>
<body>
<form action="{% url 'profiles:search' %}">
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo"
                                                href="{% url 'profiles:homepage' %}">Circle</a>
          </h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <input type="text" placeholder="Search Projects..."
                   name="search_term">
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">

              {% if not user.is_authenticated %}
                <li>
                  <a href="{% url 'password_reset' %}">
                    Forgot password?
                  </a>
                </li>
                <li>
                  <a href="{% url 'accounts:signup' %}">
                    Sign Up
                  </a>
                </li>
                <li>
                  <a href="{% url 'login' %}">
                    Sign In
                  </a>
                </li>
              {% else %}
                {% if request.user.notifications.unread %}
                  <li>
                    <a style="color:white"
                       href="{% url 'notification_hub:unread' %}">
                      <u>Unread Notifications!</u>
                    </a>
                  </li>
                {% endif %}
                <li>
                  <a href="{% url 'profiles:profile' pk=user.pk %}">
                    Your profile
                  </a>
                </li>
                <li>
                  <a href="{% url 'accounts:logout' %}">
                    Log out
                  </a>
                </li>
              {% endif %}


            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
</form>

{% block content %}{% endblock %}


</body>
</html>

team_builder/templates/nav_bar.html
{% extends "layout.html" %}

{% block title_tag %}Team Builder | profile{% endblock %}

{% block content %}

  {#    If the user is not logged in, don't show the nav bar#}
  {% if request.user.is_authenticated %}
    <div class="circle--actions--bar">
      <nav class="bounds">
        <ul class="circle--pill--list">

          <li>
            <a {% if current_tab == "Applications" %}
              class="selected" {% endif %}
              href={% url 'profiles:applications' %}>Applications</a>
          </li>
          <li>
            <a {% if current_tab == "Profile" %} class="selected" {% endif %}
                                                 href={% url 'profiles:profile' pk=user.pk %}>
              Profile
            </a>
          </li>
          <li>
            <a {% if current_tab == "My Projects" %}
              class="selected" {% endif %}
              href={% url 'profiles:project_view_all' %}>
              My Projects
            </a>
          </li>
          <li>
            <a {% if current_tab == "Notifications" %}
              class="selected" {% endif %}
              href={% url 'notification_hub:unread' %}>
              Notifications
            </a>
          </li>
          {% if request.user.is_staff or request.user.is_superuser %}
            <li>
              <a {% if current_tab == "Administrative" %}
                class="selected" {% endif %}
                href={% url 'profiles:administrative' %}>
                Administrative
              </a>
            </li>
          {% endif %}

        </ul>
      </nav>
    </div>
  {% endif %}

  {% block nav_bar %}{% endblock nav_bar %}

{% endblock content %}

team_builder/templates/selectable_list.html
{% extends "nav_bar.html" %}
{% load static %}

{% block title_tag %}Team Builder | profile{% endblock %}


Profile/nav_bar.html takes one parameter
1) current_tab
Allows the main profile header bar to change in html

The selectable_list.html template takes up to

1) block title_tab: This allows the title tag to be changed

2) block header: Allows the primary title to be changed

3) first_sidebar: The primary navigation for the sidebar

4) second_sidebar: This is the second sidebar

5) third_sidebar: This is the third sidebar

6) body_header: The main title for the body

7) body: This is the main body content


{% block nav_bar %}
  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      {# Allows the header to be changed #}
      {% block header %}{% endblock header %}
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">

          {# Allows the user to customize the first sidebar #}
          {% block first_sidebar %}
          {% endblock first_sidebar %}


        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        {# Allows the second sidebar to be changed #}
        {% block second_sidebar %}
        {% endblock second_sidebar %}
      </div>

      <div class="circle--filter circle--secondary--module">

        {# Allows the third sidebar to be changed #}
        {# Allows the the needs tag to be changed #}
        {% block third_sidebar %}
        {% endblock third_sidebar %}
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
        <tr>
          {# Allows the body_header to change #}
          {% block body_header %}

            {#  This is the format the body_header should be in #}
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          {% endblock body_header %}

        </tr>
        </thead>
        <tbody>

        {# Allows the main body content to be changed #}
        {% block body %}
        {% endblock body %}


        </tbody>
      </table>

    </div>

  </div>
{% endblock nav_bar %}