team_builder/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'email_confirmation/',
        views.email_confirmation_view,
        name='email_confirmation'
    ),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path(
        'token_confirmation/<str:token>/',
        views.token_confirmation,
        name='token_confirmation'
    ),
]

team_builder/notification_hub/urls.py
from django.urls import path

from . import views

app_name = 'notification_hub'

urlpatterns = [
    path('all/', views.notifications, name='notifications'),
    path(
        'deletion/<int:pk>',
        views.delete,
        name='delete'
    ),
    path(
        'deletion_view',
        views.deletion_view,
        name='deletion_view'
    ),
    path(
        'mark_read/<int:pk>/',
        views.mark_read,
        name='mark_read'
    ),
    path(
        'mark_unread/<int:pk>/',
        views.mark_unread,
        name='mark_unread'
    ),
    path(
        'unread',
        views.unread,
        name='unread'
    ),
    path(
        'read',
        views.read,
        name='read'
    ),
]

team_builder/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'

urlpatterns = [
    # Miscellaneous related paths
    path('', views.HomepageListView.as_view(), name='homepage'),
    path('login_router', views.login_router, name='login_router'),
    path('new_skill', views.new_skill, name='new_skill'),

    # Administrative related paths
    path('administrative', views.administrative, name='administrative'),
    path(
        'administrative/non_pending',
        views.administrative_non_pending,
        name='administrative_non_pending'
    ),
    path(
        'administrative/skill/<int:pk>/accept',
        views.skill_accept,
        name='skill_accept'
    ),
    path(
        'administrative/skill/<int:pk>/deny',
        views.skill_deny,
        name='skill_deny'
    ),

    # Applications related paths
    path('applications', views.applications, name='applications'),

    path('applications/accept/<int:position_pk>/<int:profile_pk>',
         views.applications_accept,
         name='applications_accept'),

    path('applications/reject/<int:position_pk>/<int:profile_pk>',
         views.applications_reject,
         name='applications_reject'),

    path('applications/request/<int:pk>',
         views.applications_request,
         name='applications_request'),

    path('applications/view/accepted',
         views.applications_view_accepted,
         name='applications_view_accepted'),

    path('applications/view/rejected',
         views.applications_view_rejected,
         name='applications_view_rejected'),

    # Profile related paths
    path('profile/edit/', views.profile_edit, name='edit'),
    path(
        'profile/edit/image/',
        views.profile_edit_image,
        name='profile_edit_image'
    ),
    path(
        'profile/view/<int:pk>/',
        views.profile_view,
        name='profile'
    ),

    # Project related paths
    path(
        'project/delete/<int:pk>',
        views.project_delete,
        name='project_delete'
    ),
    path(
        'project/delete_confirmation/<int:pk>',
        views.project_delete_confirmation,
        name='project_delete_confirmation'
    ),
    path('project/edit/<int:pk>', views.project_edit, name='project_edit'),
    path('project/new', views.project_new, name='project_new'),
    path('project/view/<int:pk>/', views.project_view, name='project'),
    path('project/view_all', views.project_view_all, name='project_view_all'),

    # Search related paths
    path('search', views.SearchListView.as_view(), name='search'),
    path(
        'search/skill/<str:skill>',
        views.SearchBySkillListView.as_view(),
        name='search_by_skill'
    ),
    path('search/your_skills',
         views.SearchYourSkillsView.as_view(),
         name='search_your_skills'
    ),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# django-notifications
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'),),
    path('accounts/', include('django.contrib.auth.urls'),),
    url('^inbox/notifications/',
        include(notifications.urls, namespace='notifications')
        ),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^notifications/', include('notification_hub.urls')),
    path('', include('profiles.urls'))
]

# Enable the Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

team_builder/profiles/views/admin.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render


from .. import models


def admin_or_staff(user) -> bool:
    """
    Checks to see if a user is an admin or staff

    :param user: Standard User model
    :return: Bool stating if the user is an admin or staff
    """
    if user.is_staff or user.is_superuser:
        return True
    return False


@login_required
def administrative(request):
    """
    Shows an Admin/staff user the administrative page

    :param request: Standard django request object
    :return: render 'profiles/administrative.html'
    """
    logged_in_user = request.user
    if not admin_or_staff(logged_in_user):
        raise Http404('You are not an admin or staff user!')

    tasks = models.SkillConfirmation.objects.filter(pending=True)

    return render(
        request,
        'profiles/administrative.html',
        {
            'current_tab': 'Administrative',  # navigation bar selector
            'tasks': tasks

        }
    )


@login_required
def administrative_non_pending(request):
    """
    Shows an Admin/staff user the administrative page for non_pending items
    """
    logged_in_user = request.user
    if not admin_or_staff(logged_in_user):
        raise Http404('You are not an admin or staff user!')

    tasks = (
        models.SkillConfirmation.objects.filter(pending=False).order_by('-pk')
    )

    return render(
        request,
        'profiles/administrative_non_pending.html',
        {
            'current_tab': 'Administrative',  # navigation bar selector
            'tasks': tasks

        }
    )


@login_required
def skill_accept(request, pk: int):
    """
    Creates a Skill object From a SkillConfirmation object
    The new skill is added to the creator's AllSkills model

    :param request: Standard django request object
    :param pk: The pk of a SkillConfirmation object
    :return: redirect to 'profiles:administrative'
    """
    logged_in_user = request.user
    if not admin_or_staff(logged_in_user):
        raise Http404('You are not an admin or staff user!')

    skill_confirmation = get_object_or_404(models.SkillConfirmation, pk=pk)
    skill = models.Skill.objects.get_or_create(skill=skill_confirmation.skill)

    user = skill_confirmation.creator
    user.allskills.skills.add(skill[0])  # Skill is a tuple

    skill_confirmation.pending = False
    skill_confirmation.accepted = True
    skill_confirmation.save()

    return redirect('profiles:administrative')


@login_required
def skill_deny(request, pk: int):
    """
    Denys a SkillConfirmation request and closes the request

    :param request: Standard django request object
    :param pk: The pk of a SkillConfirmation object
    :return: render redirect to 'profiles:administrative'
    """
    logged_in_user = request.user
    if not admin_or_staff(logged_in_user):
        raise Http404('You are not an admin or staff user!')

    skill_confirmation = get_object_or_404(models.SkillConfirmation, pk=pk)
    skill_confirmation.pending = False
    skill_confirmation.save()

    return redirect('profiles:administrative')

team_builder/profiles/views/administrative.py
from django.shortcuts import get_object_or_404, redirect, render

from .. import models
from ..decorators import logged_in_admin_or_staff_required


@logged_in_admin_or_staff_required
def administrative(request):
    """
    Shows an Admin/staff user the administrative page

    :param request: Standard django request object
    :return: render 'profiles/administrative.html'
    """

    tasks = models.SkillConfirmation.objects.filter(pending=True)\
        .prefetch_related('creator')

    return render(
        request,
        'profiles/administrative.html',
        {
            'current_tab': 'Administrative',  # navigation bar selector
            'tasks': tasks

        }
    )


@logged_in_admin_or_staff_required
def administrative_non_pending(request):
    """
    Shows an Admin/staff user the administrative page for non_pending items

    :param request: Standard django request object
    :return: render 'profiles/administrative_non_pending.html'
    """

    tasks = (
        models.SkillConfirmation.objects
        .filter(pending=False)
        .order_by('-pk')
        .prefetch_related('creator')
             )

    return render(
        request,
        'profiles/administrative_non_pending.html',
        {
            'current_tab': 'Administrative',  # navigation bar selector
            'tasks': tasks

        }
    )


@logged_in_admin_or_staff_required
def skill_accept(request, pk: int):
    """
    Creates a Skill object From a SkillConfirmation object
    The new skill is added to the creator's AllSkills model

    :param request: Standard django request object
    :param pk: The pk of a SkillConfirmation object
    :return: redirect to 'profiles:administrative'
    """

    skill_confirmation = get_object_or_404(models.SkillConfirmation, pk=pk)
    skill = models.Skill.objects.get_or_create(skill=skill_confirmation.skill)

    user = skill_confirmation.creator
    user.allskills.skills.add(skill[0])  # Skill is a tuple

    skill_confirmation.pending = False
    skill_confirmation.accepted = True
    skill_confirmation.save()

    return redirect('profiles:administrative')


@logged_in_admin_or_staff_required
def skill_deny(request, pk: int):
    """
    Denys a SkillConfirmation request and closes the request

    :param request: Standard django request object
    :param pk: The pk of a SkillConfirmation object
    :return: render redirect to 'profiles:administrative'
    """

    skill_confirmation = get_object_or_404(models.SkillConfirmation, pk=pk)
    skill_confirmation.pending = False
    skill_confirmation.save()

    return redirect('profiles:administrative')

team_builder/profiles/views/miscellaneous_views.py
from operator import attrgetter

from django.views.generic import ListView

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

# django-notifications-hq
from notifications.signals import notify

from ..forms import NewSkillFormSet
from .. import models


def create_skill_confirmation(user, skill: int):
    """
    Creates a SkillConfirmation object and sends a notification to
    all staff or admins that a new skill has been requested

    :param user: The user who will own the SkillConfirmation
    :param skill: The string of the skill
    """
    skill = models.SkillConfirmation.objects.create(creator=user, skill=skill)

    user_model = get_user_model()

    staff = user_model.objects.filter(is_staff=True, is_superuser=True)

    message = f'Pending skill: "{skill.skill}" waiting for approval'

    for person in staff:
        notify.send(user, recipient=person, verb=message)


"""Miscellaneous views"""


class HomepageListView(ListView):
    """This is the homepage for the profiles app"""
    model = models.Project
    template_name = 'profiles/homepage.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        # gets skills for the template
        context = super(HomepageListView, self).get_context_data(**kwargs)
        context['skills'] = (
            sorted(models.Skill.objects.all(), key=attrgetter('skill'))
        )
        return context

    def get_queryset(self):
        """Returns all Projects that have an unfilled position"""
        return (
            models.Project.objects.filter(
                positions__filled=False
            ).distinct().prefetch_related('positions__skill')
        )


@login_required
def login_router(request):
    """
    Check to see if the user's profile has been edited.

    If not: route to the profile edit page and attach skills
    Else: route to the main profile page
    """

    user = request.user

    # Checks if an AllSkills model is attached to the user
    # If not create and send to edit page
    try:
        user = user.allskills
    except AttributeError:
        models.AllSkills.objects.create(
            user_id=user.pk
        )

        # Redirect to the main edit page
        return redirect('profiles:edit')

    else:
        # redirect to main profile page
        return redirect('profiles:profile', pk=request.user.pk)


@login_required
def new_skill(request):
    """
    Allows a user to request new skills.

    :param request: Standard django request object
    :return: redirect to 'profiles:profile'
    """
    user = request.user
    if request.POST:
        skills_form = NewSkillFormSet(request.POST)

        if skills_form.is_valid():
            skills_dict = skills_form.cleaned_data

            for skill in skills_dict:
                # Check if the skill already exists

                try:
                    found_skill = models.Skill.objects.get(
                        skill__icontains=skill['skill']
                    )

                except:
                    # Check if the user is a superuser or staff
                    # If so create
                    if user.is_staff or user.is_superuser:
                        latest_skill = models.Skill.objects.create(
                            skill=skill['skill']
                        )
                        user.allskills.skills.add(latest_skill)
                    else:
                        create_skill_confirmation(user, skill['skill'])

                else:
                    # Add the found skill to the user
                    user.allskills.skills.add(found_skill)

            return redirect('profiles:profile', pk=user.pk)

    initial = [{'skill': ''}]
    skills_form = NewSkillFormSet(initial=initial)
    return render(
        request,
        'profiles/new_skill.html',
        {
            'current_tab': 'Profile',  # navigation bar selector
            'skills_form': skills_form,
            'user': user
        }
    )

team_builder/profiles/templates/profiles/accepted_applicants.html
{%  extends "profiles/applications.html" %}


{% block header %}<h2>Accepted Applicants</h2>{% endblock header %}


{% block projects %}
  <div class="circle--filter circle--secondary--module">
    <h4>Filled Projects</h4>
    <ul class="circle--filter--list">
        {% for project in projects %}
            <li>
                <a href="{% url 'profiles:project' pk=project.pk %}">
                    {{ project|truncatechars:25 }}
                </a>
            </li>
        {% endfor %}
        {% if not projects %}
            <li>You have no filled projects.</li>
        {% endif %}
    </ul>
  </div>
{% endblock projects %}


{% block applicants %}
    {% if not found_positions %}
        <h2>You have no accepted positions</h2>
    {% endif %}

    {% for applicant in found_positions %}
          <tr class="clickable-row" data-href="">
            <td>

                <h3>
                    <a href=" {% url 'profiles:profile' pk=applicant.pk %}">
                        {{ applicant }}
                    </a>
                </h3>
                <p>
                    <a href=" {% url 'profiles:project' pk=applicant.position.related_project.pk  %}">
                        {{ applicant.position.related_project }}
                    </a>
                </p>

            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ applicant.position.skill }}
              </span>
            </td>
          </tr>
    {% endfor %}
{% endblock applicants %}


{% block needs %}<h4>Filled Needs</h4>{% endblock needs %}

team_builder/profiles/templates/profiles/administrative_non_pending.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


{% block title_tag %}Team Builder | Administrative{% endblock title_tag %}
{% block header %}<h2>Administrative</h2>{% endblock header %}


{% block first_sidebar %}
  <li>
    <a href="{% url 'profiles:administrative' %}">
      Pending Tasks
    </a>
  </li>
  <li>
    <a class="selected" href="{% url 'profiles:administrative_non_pending' %}">
      Non-pending Tasks
    </a>
  </li>

{% endblock first_sidebar %}


{% block body_header %}
  <th>Task</th>
  <th class="circle--cell--right">Accept/Deny</th>
{% endblock body_header %}


{% block body %}
  {% if not tasks %}
    <h2>There are no non-pending Admin tasks</h2>
  {% endif %}

  {% for task in tasks %}
    <tr class="clickable-row" data-href="">
      <td>
        <h3>
          <a>
            {{ task }}
          </a>
        </h3>
        <p>
          <a href={% url 'profiles:profile' pk=1 %}>
            From: {{ task.creator }}
          </a>
        </p>


      </td>
      <td class="circle--cell--right">

        {% if task.accepted %}
          <a class="button">
            Accepted
          </a>
        {% else %}
          <a class="button button-secondary">
            Rejected
          </a>
        {% endif %}

        </span>
      </td>
    </tr>
  {% endfor %}
{% endblock body %}

team_builder/profiles/templates/profiles/applicants_rejected.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


applicants_rejected.html takes a couple of parameters

1) found_positions
  All of the Applicants that meet the search criteria
2) needed skills
  This is all of the skills that applicants have applied for
3) projects
  All of the projects that meet the search criteria


{% block title_tag %}Team Builder | Applications{% endblock %}


{% block header %}<h2>Rejected Applications</h2>{% endblock header %}

{% block first_sidebar %}
  <li>
    <a href="{% url 'profiles:applications' %}">
      All Open Applications
    </a>
  </li>
  <li>
    <a href="{% url 'profiles:applications_view_accepted' %}">
      Accepted
    </a>
  </li>
  <li>
    <a class="selected" href="{% url 'profiles:applications_view_rejected' %}">
      Rejected
    </a>
  </li>
{% endblock first_sidebar %}


{% block second_sidebar %}
  <h4>Rejected Projects</h4>
  <ul class="circle--filter--list">
    {% for project in projects %}
      <li>
        <a href="{% url 'profiles:project' pk=project.pk %}">
          {{ project|truncatechars:25 }}
        </a>
      </li>
    {% endfor %}
    {% if not projects %}
      <li>You have no projects with rejections.</li>
    {% endif %}
  </ul>
{% endblock second_sidebar %}


{% block third_sidebar %}
  <div class="circle--filter circle--secondary--module">
    <h4>Project Needs</h4>
    <ul class="circle--filter--list">
      <li><a class="selected">Rejected Needs</a></li>
      {% for need in needed_skills %}
        <li>
          <a>{{ need }}</a>
        </li>
      {% endfor %}

      {% if not needed_skills %}
        <p>There are no applicants</p>
      {% endif %}
    </ul>
  </div>
{% endblock third_sidebar %}


{% block body_header %}
  <th>Applicant</th>
  <th class="circle--cell--right">Applicant Position</th>
{% endblock body_header %}


{% block body %}
  {% if not found_positions %}
    <h2>You have no rejected positions</h2>
  {% endif %}

  {% for applicant in found_positions %}
    <tr class="clickable-row" data-href="">
      <td>

        <h3>
          <a href=" {% url 'profiles:profile' pk=applicant.pk %}">
            {{ applicant }}
          </a>
        </h3>
        <p>
          <a href=" {% url 'profiles:project' pk=applicant.position.related_project.pk %}">
            {{ applicant.position.related_project }}
          </a>
        </p>

      </td>
      <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ applicant.position.skill }}
              </span>
      </td>
    </tr>
  {% endfor %}
{% endblock body %}

team_builder/profiles/templates/profiles/layout.html
{% extends "layout.html" %}

{% block title_tag %}Team Builder | profile{% endblock %}

{% block content %}

{#    If the user is not logged in, don't show the nav bar#}
    {% if request.user.is_authenticated %}
      <div class="circle--actions--bar">
        <nav class="bounds">
          <ul class="circle--pill--list">

            <li>
              <a {% if current_tab == "Applications" %} class="selected" {% endif %}
                      href={% url 'profiles:applications'%}>Applications</a>
            </li>
            <li>
                <a {% if current_tab == "Profile" %} class="selected" {% endif %}
                        href={% url 'profiles:profile' pk=user.profile.pk %}>
                    Profile
                </a>
            </li>
            <li>
                <a {% if current_tab == "My Projects" %} class="selected" {% endif %}
                        href={% url 'profiles:project_view_all' %}>
                    My Projects
                </a>
            </li>

          </ul>
        </nav>
      </div>
    {% endif %}

  {% block profiles_content %}{% endblock profiles_content %}

{% endblock content %}

team_builder/profiles/templates/profiles/notifications.html
{% extends "profiles/selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
    Allows the main profile header bar to change in html


Notifications.html takes a couple of parameters

1) notification_query
    The notifications that a user has



{% block title_tag %}Team Builder | Notifications{% endblock title_tag %}


{% block header %}<h2>Notifications</h2>{% endblock header %}


{% block first_sidebar %}
    <li>
      <a class="selected" href="{% url 'profiles:notifications' %}">
          All Notifications
      </a>
    </li>
    <li>
      <a href="{% url 'profiles:notifications_unread' %}">
          Unread
      </a>
    </li>
    <li>
      <a href="{% url 'profiles:notifications_read' %}">
          Read
      </a>
    </li>
    <li>
      <a href="{% url 'profiles:notifications_deletion_view' %}">
          Deletion View
      </a>
    </li>
{% endblock first_sidebar %}


{% block body_header %}
    <th>Notifications</th>
    <th class="circle--cell--right">Time of notification</th>
{% endblock body_header %}


{% block body %}
    {% if not notification_query %}
        <h2>You have no notifications.</h2>
    {% endif %}

    {% for notification in notification_query %}
          <tr class="clickable-row" data-href="">
            <td>
                <h3>
                    <a>
                        {{ notification.verb }}
                    </a>
                </h3>
                <p>
                    <a href={% url 'profiles:profile' pk=notification.actor.pk%}>
                        {% if notification.unread %}
                            Unread from: {{ notification.actor}}
                        {% else %}
                            Read from: {{ notification.actor}}
                        {% endif %}
                    </a>
                </p>


            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ notification.timestamp }}
              </span>
            </td>
          </tr>
    {% endfor %}
{% endblock body %}

team_builder/profiles/templates/profiles/profile.html
{% extends "nav_bar.html" %}
{% load static %}

{% block title_tag %}Team Builder | profile{% endblock %}

{% block nav_bar %}

  <div class="bounds circle--page">
  <div class="circle--page--header circle--fluid">
    {% if user_profile.username == request.user.username %}
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>{{ user_profile.username }}'s profile</h2>
      </div>
    {% else %}
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Viewing {{ user_profile.username }}'s profile</h2>
      </div>
    {% endif %}


    {#      If the logged in user is not the same as the user_profile#}
    {#        don't show an edit button#}
    {% if user_profile.username == request.user.username %}
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button icon-on-left" href="{% url 'profiles:edit' %}">
          Edit
        </a>
      </div>
    {% endif %}


  </div>

  <div class="grid-70">
    <div class="circle--article--body">
      <h2>Bio:</h2>
      <p>{{ user_profile.bio_markdown|safe }}</p>
    </div>

    <h2>Past Projects</h2>
    <table class="u-full-width circle--table">
      <thead>
      <tr>
        <th>Project Title</th>
        <th class="circle--cell--right">Project Positions</th>
      </tr>
      </thead>
      <tbody>

      {% for project in projects %}
        <tr class="clickable-row"
            data-href="{% url 'profiles:project' pk=project.pk %}">
          <td>
            <h3>{{ project }}</h3>
          </td>

          {% with project.positions.all as positions %}

            {% if positions|length > 3 %}
              <td class="circle--cell--right">
                    <span class="secondary-label">
                        <b><i>Many Positions</i></b>
                    </span>
              </td>
            {% else %}
              {% for position in positions %}
                <td class="circle--cell--right">
                          <span class="secondary-label">
                              {{ position.skill }}
                          </span>
                </td>
              {% endfor %}
            {% endif %}

          {% endwith %}

        </tr>
      {% endfor %}


      </tbody>
    </table>
  </div>

  <div class="grid-25 grid-push-5">

  {#    Checks to see if the user has an avatar.#}
  {#    If not use default profile media#}
  {% if user_profile.avatar %}
    <div class="circle--secondary--module">
      <img class="circle--primary--avatar"
           src="{% static user_profile.avatar.url %}">
    </div>
  {% else %}
    <div class="circle--secondary--module">
      <img class="circle--primary--avatar"
           src="{% static 'profiles_media/default_profile_image.png' %}"/>
    </div>
  {% endif %}

  {% if user_profile.username == request.user.username %}
    <p>
      <a href="{% url 'profiles:profile_edit_image' %}">
        Image editor
      </a>
    </p>
  {% endif %}

  <div class="circle--secondary--module">
    <h4>My Skills</h4>
    <ul class="unloaded">
      {% for skill in user_profile.allskills.skills.all %}
        <li>{{ skill }}</li>
      {% endfor %}
    </ul>
  </div>


{% endblock nav_bar %}

team_builder/profiles/templates/profiles/project.html
{% extends "layout.html" %}

{% block content %}


  {% if user.username == project.owner.username %}
    <div class="circle--actions--bar">
      <div class="bounds">
        <div class="grid-100">


          {#      Lets the header content be changed for delete_confirmation  #}
          {% block delete_confirmation_header %}
            <a class="button"
               href="{% url 'profiles:project_edit' pk=project.pk %}">
              Edit Project
            </a>
          {% endblock delete_confirmation_header %}


        </div>
      </div>
    </div>
  {% endif %}

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project }}</h1>
        <p class="circle--article--byline">Project Owner:
          <a href="{% url 'profiles:profile' pk=project.owner.pk %}">
            {{ project.owner }}
          </a>
        </p>
      </div>

      <div class="circle--article--body">
        <h4 class="circle--article--section">Description</h4>
        {{ project.description_markdown|safe }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list">

          {% block applicant_buttons %}

            {% for position in unfilled_positions %}
              <h3>{{ position.skill }}</h3>
              <h4><u>Information</u></h4>
              <p>{{ position.information|linebreaks }}</p>
              <h4><u>Time Commitment</u></h4>
              <p>{{ position.time_commitment_markdown|safe }}</p>

              <a class="button button-primary"
                 href="{% url 'profiles:applications_request' pk=position.pk %}">
                Apply
              </a>
            {% endfor %}
            </ul>

            <h2>Filled Positions</h2>
            <ul class="circle--group--list">
              {% for position in filled_positions %}
                <h3>{{ position.skill }}</h3>
                <h4><u>Information</u></h4>
                <p>{{ position.information|linebreaks }}</p>
                <h4><u>Time Commitment</u></h4>
                <p>{{ position.time_commitment_markdown|safe }}</p>

                <a class="button button-primary button-inactive">
                  Position Filled
                </a>

              {% endfor %}
            </ul>

          {% endblock applicant_buttons %}


        {#        Allows for the addition of delete_confirmation form buttons#}
        {% block delete_confirmation %}
        {% endblock delete_confirmation %}

      </div>
    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        <ul class="circle--link--list">
          {% for position in unfilled_positions %}
            <li><a>{{ position }}</a></li>
          {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.time_line }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ project.requirements }}</p>
      </div>

    </div>
  </div>
{% endblock content %}

team_builder/profiles/templates/profiles/project_view_owned.html
{% extends "profiles/project.html" %}

{% block applicant_buttons %}

  {% for position in unfilled_positions %}
    <h3>{{ position.skill }}</h3>
    <h4><u>Information</u></h4>
    <p>{{ position.information|linebreaks }}</p>
    <h4><u>Time Commitment</u></h4>
    <p>{{ position.time_commitment_markdown|safe }}</p>

    <a class="button button-primary">Accepting applicants</a>

  {% endfor %}
  </ul>

  <h2>Filled Positions</h2>
  <ul class="circle--group--list">
    {% for position in filled_positions %}
      <h3>{{ position.skill }}</h3>
      <h4><u>Information</u></h4>
      <p>{{ position.information|linebreaks }}</p>
      <h4><u>Time Commitment</u></h4>
      <p>{{ position.time_commitment_markdown|safe }}</p>

      <a class="button button-primary button-inactive"
         href="{% url 'profiles:profile' pk=position.filled_by.pk %}">
        Position Filled by {{ position.filled_by }}
      </a>

    {% endfor %}
  </ul>

{% endblock applicant_buttons %}