team_builder/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'email_confirmation/',
        views.email_confirmation_view,
        name='email_confirmation'
    ),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign_up, name='signup'),
    path(
        'token_confirmation/<str:token>/',
        views.token_confirmation,
        name='token_confirmation'
    ),
]

team_builder/notification_hub/urls.py
from django.urls import path

from . import views

app_name = 'notification_hub'

urlpatterns = [
    path('all/', views.notifications, name='notifications'),
    path(
        'deletion/<int:pk>',
        views.delete,
        name='delete'
    ),
    path(
        'deletion_view',
        views.deletion_view,
        name='deletion_view'
    ),
    path(
        'mark_read/<int:pk>/',
        views.mark_read,
        name='mark_read'
    ),
    path(
        'mark_unread/<int:pk>/',
        views.mark_unread,
        name='mark_unread'
    ),
    path(
        'unread',
        views.unread,
        name='unread'
    ),
    path(
        'read',
        views.read,
        name='read'
    ),
]

team_builder/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'

urlpatterns = [
    # Miscellaneous related paths
    path('', views.HomepageListView.as_view(), name='homepage'),
    path('login_router', views.login_router, name='login_router'),
    path('new_skill', views.new_skill, name='new_skill'),

    # Administrative related paths
    path('administrative', views.administrative, name='administrative'),
    path(
        'administrative/non_pending',
        views.administrative_non_pending,
        name='administrative_non_pending'
    ),
    path(
        'administrative/skill/<int:pk>/accept',
        views.skill_accept,
        name='skill_accept'
    ),
    path(
        'administrative/skill/<int:pk>/deny',
        views.skill_deny,
        name='skill_deny'
    ),

    # Applications related paths
    path('applications', views.applications, name='applications'),

    path('applications/accept/<int:position_pk>/<int:profile_pk>',
         views.applications_accept,
         name='applications_accept'),

    path('applications/reject/<int:position_pk>/<int:profile_pk>',
         views.applications_reject,
         name='applications_reject'),

    path('applications/request/<int:pk>',
         views.applications_request,
         name='applications_request'),

    path('applications/view/accepted',
         views.applications_view_accepted,
         name='applications_view_accepted'),

    path('applications/view/rejected',
         views.applications_view_rejected,
         name='applications_view_rejected'),

    # Profile related paths
    path('profile/edit/', views.profile_edit, name='edit'),
    path(
        'profile/edit/image/',
        views.profile_edit_image,
        name='profile_edit_image'
    ),
    path(
        'profile/view/<int:pk>/',
        views.profile_view,
        name='profile'
    ),

    # Project related paths
    path(
        'project/delete/<int:pk>',
        views.project_delete,
        name='project_delete'
    ),
    path(
        'project/delete_confirmation/<int:pk>',
        views.project_delete_confirmation,
        name='project_delete_confirmation'
    ),
    path('project/edit/<int:pk>', views.project_edit, name='project_edit'),
    path('project/new', views.project_new, name='project_new'),
    path('project/view/<int:pk>/', views.project_view, name='project'),
    path('project/view_all', views.project_view_all, name='project_view_all'),

    # Search related paths
    path('search', views.SearchListView.as_view(), name='search'),
    path(
        'search/skill/<str:skill>',
        views.SearchBySkillListView.as_view(),
        name='search_by_skill'
    ),
    path('search/your_skills',
         views.SearchYourSkillsView.as_view(),
         name='search_your_skills'
    ),
]

team_builder/team_builder/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# django-notifications
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'),),
    path('accounts/', include('django.contrib.auth.urls'),),
    url('^inbox/notifications/',
        include(notifications.urls, namespace='notifications')
        ),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^notifications/', include('notification_hub.urls')),
    path('', include('profiles.urls'))
]

# Enable the Django Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

team_builder/notification_hub/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render


def get_notification_and_authenticate(request, pk: int):
    """
    Gets the logged in user and makes sure that the user owns
    the notification

    :param request: The standard django request object
    :param pk: The primary key of a user

    :return: If the user owns the notification, return notification
    :else: raise 404
    """
    user = request.user

    # Get the notification or 404
    notification = get_object_or_404(user.notifications, pk=pk)

    # If the user does not own the notification 404
    if notification.recipient == user:
        Http404('You do not own this notification')

    return notification


"""Notification Views"""


@login_required
def notifications(request):
    """
    This is the main notification view for a user

    :param request: The standard django request object

    :return: render request for 'notifications.html'
    """
    notification_query = (
        request.user.notifications.all().prefetch_related("actor")
    )

    return render(
        request,
        'notification_hub/notifications.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def delete(request, pk: int):
    """
    Marks a notification as read and reroute back to
    notification_hub:unread

    :param request: The standard django request object
    :param pk: The primary key of a notification

    :return: redirect to 'notification_hub:deletion_view'
    """
    notification = get_notification_and_authenticate(request, pk)

    # mark the notification as read
    notification.delete()

    return redirect('notification_hub:deletion_view')


@login_required
def deletion_view(request):
    """
    Shows the user all read notifications that they can delete

    :param request: The standard django request object

    :return: render request for 'deletion.html'
    """
    notification_query = (
        request.user.notifications.read().prefetch_related('actor')
    )

    return render(
        request,
        'notification_hub/deletion.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def mark_read(request, pk: int):
    """
    Marks a notification as read and reroute back to
    notification_hub:unread

    :param request: The standard django request object
    :param pk: The primary key of a notification

    :return: redirect to 'notification_hub:unread'
    """
    notification = get_notification_and_authenticate(request, pk)

    # mark the notification as read
    notification.mark_as_read()

    return redirect('notification_hub:unread')


@login_required
def mark_unread(request, pk: int):
    """
    Marks a notification as unread and reroute back to the route
    'notification_hub:read'

    :param request: The standard django request object
    :param pk: The primary key of a notification

    :return: redirect to 'notification_hub:read'
    """
    notification = get_notification_and_authenticate(request, pk)

    # mark the notification as read
    notification.mark_as_unread()

    return redirect('notification_hub:read')


@login_required
def read(request):
    """
    Shows the user all their opened notifications

    :param request: The standard django request object

    :return: render request 'read.html'
    """
    notification_query = (
        request.user.notifications.read().prefetch_related('actor')
    )

    return render(
        request,
        'notification_hub/read.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def unread(request):
    """
    Shows the user all their unopened notifications

    :param request: The standard django request object

    :return: render request 'unread.html'
    """
    notification_query = (
        request.user.notifications.unread().prefetch_related('actor')
    )

    return render(
        request,
        'notification_hub/unread.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )

team_builder/profiles/views/notification_views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

"""Notification Views"""


@login_required
def notifications(request):
    """This is the main notification view for a user"""
    notification_query = request.user.notifications.all()\
        .prefetch_related("actor")

    return render(
        request,
        'profiles/notifications.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def notifications_delete(request, pk):
    """Marks a notification as read and reroute back to
     profiles:notifications_unread"""
    user = request.user

    # Get the notification or 404
    notification = get_object_or_404(user.notifications, pk=pk)

    # If the user does not own the notification 404
    if notification.recipient == user:
        Http404('You do not own this notification')

    # mark the notification as read
    notification.delete()

    return redirect('profiles:notifications_deletion_view')


@login_required
def notifications_deletion_view(request):
    """Shows the user all read notifications that they can delete"""
    notification_query = request.user.notifications.read()

    return render(
        request,
        'profiles/notifications_deletion.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def notifications_mark_read(request, pk):
    """Marks a notification as read and reroute back to
     profiles:notifications_unread"""
    user = request.user

    # Get the notification or 404
    notification = get_object_or_404(user.notifications, pk=pk)

    # If the user does not own the notification 404
    if notification.recipient == user:
        Http404('You do not own this notification')

    # mark the notification as read
    notification.mark_as_read()

    return redirect('profiles:notifications_unread')


@login_required
def notifications_mark_unread(request, pk):
    """Marks a notification as unread and reroute back to
     profiles:notifications_read"""
    user = request.user

    # Get the notification or 404
    notification = get_object_or_404(user.notifications, pk=pk)

    # If the user does not own the notification 404
    if notification.recipient == user:
        Http404('You do not own this notification')

    # mark the notification as read
    notification.mark_as_unread()

    return redirect('profiles:notifications_read')


@login_required
def notifications_read(request):
    """Shows the user all their opened notifications"""
    notification_query = request.user.notifications.read()

    return render(
        request,
        'profiles/notifications_read.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )


@login_required
def notifications_unread(request):
    """Shows the user all their unopened notifications"""
    notification_query = request.user.notifications.unread()

    return render(
        request,
        'profiles/notifications_unread.html',
        {
            'current_tab': 'Notifications',
            'notification_query': notification_query
        }
    )

team_builder/notification_hub/templates/notification_hub/deletion.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


Notifications.html takes a couple of parameters

1) notification_query
  The notifications that a user has


{% block title_tag %}Team Builder | Notifications{% endblock title_tag %}
{% block header %}<h2>Notifications</h2>{% endblock header %}


{% block first_sidebar %}
  <li>
    <a href="{% url 'notification_hub:notifications' %}">
      All Notifications
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:unread' %}">
      Unread
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:read' %}">
      Read
    </a>
  </li>
  <li>
    <a class="selected" href="{% url 'notification_hub:deletion_view' %}">
      Deletion View
    </a>
  </li>
{% endblock first_sidebar %}


{% block body_header %}
  <th>Read notifications for deletion</th>
  <th class="circle--cell--right">Time of notification</th>
{% endblock body_header %}


{% block body %}
  {% if not notification_query %}
    <h2>You have no read notifications.</h2>
  {% endif %}

  {% for notification in notification_query %}
    <tr class="clickable-row" data-href="">
      <td>
        <h3>
          <a>
            {{ notification.verb }}
          </a>
        </h3>
        <p>
          <a href={% url 'profiles:profile' pk=notification.actor.pk %}>
            From: {{ notification.actor }}
          </a>
        </p>


      </td>
      <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ notification.timestamp }}
                  <a class="button button-secondary"
                     href= {% url 'notification_hub:delete' pk=notification.pk %}>
                    Delete
                  </a>
              </span>
      </td>
    </tr>
  {% endfor %}
{% endblock body %}

team_builder/notification_hub/templates/notification_hub/notifications.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


Notifications.html takes a couple of parameters

1) notification_query
  The notifications that a user has



{% block title_tag %}Team Builder | Notifications{% endblock title_tag %}
{% block header %}<h2>Notifications</h2>{% endblock header %}


{% block first_sidebar %}
  <li>
    <a class="selected" href="{% url 'notification_hub:notifications' %}">
      All Notifications
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:unread' %}">
      Unread
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:read' %}">
      Read
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:deletion_view' %}">
      Deletion View
    </a>
  </li>
{% endblock first_sidebar %}


{% block body_header %}
  <th>Notifications</th>
  <th class="circle--cell--right">Time of notification</th>
{% endblock body_header %}


{% block body %}
  {% if not notification_query %}
    <h2>You have no notifications.</h2>
  {% endif %}

  {% for notification in notification_query %}
    <tr class="clickable-row" data-href="">
      <td>
        <h3>
          <a>
            {{ notification.verb }}
          </a>
        </h3>
        <p>
          <a href={% url 'profiles:profile' pk=notification.actor.pk %}>
            {% if notification.unread %}
              Unread from: {{ notification.actor }}
            {% else %}
              Read from: {{ notification.actor }}
            {% endif %}
          </a>
        </p>

      </td>
      <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ notification.timestamp }}
              </span>
      </td>
    </tr>
  {% endfor %}
{% endblock body %}

team_builder/notification_hub/templates/notification_hub/read.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


Notifications.html takes a couple of parameters

1) notification_query
  The read notifications that a user has


{% block title_tag %}Team Builder | Notifications{% endblock title_tag %}
{% block header %}<h2>Notifications</h2>{% endblock header %}


{% block first_sidebar %}
  <li>
    <a href="{% url 'notification_hub:notifications' %}">
      All Notifications
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:unread' %}">
      Unread
    </a>
  </li>
  <li>
    <a class="selected" href="{% url 'notification_hub:read' %}">
      Read
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:deletion_view' %}">
      Deletion View
    </a>
  </li>
{% endblock first_sidebar %}


{% block body_header %}
  <th>Read Notifications</th>
  <th class="circle--cell--right">Time of notification</th>
{% endblock body_header %}


{% block body %}
  {% if not notification_query %}
    <h2>You have no read notifications</h2>
  {% endif %}

  {% for notification in notification_query %}
    <tr class="clickable-row" data-href="">
      <td>
        <h3>
          <a>
            {{ notification.verb }}
          </a>
        </h3>
        <p>

          <a href={% url 'profiles:profile' pk=notification.actor.pk %}>
            From: {{ notification.actor }}
          </a>

      </td>
      <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ notification.timestamp }}
                  <a class="button button-primary extra_vertical_margin"
                     href= {% url 'notification_hub:mark_unread' pk=notification.pk %}>
                    Mark unread
                  </a>
              </span>
      </td>

    </tr>
  {% endfor %}
{% endblock body %}

team_builder/notification_hub/templates/notification_hub/unread.html
{% extends "selectable_list.html" %}


nav_bar.html takes one parameter
1) current_tab
  Allows the main profile header bar to change in html


Notifications.html takes a couple of parameters

1) notification_query
  The unread notifications that a user has


{% block title_tag %}Team Builder | Notifications{% endblock title_tag %}
{% block header %}<h2>Notifications</h2>{% endblock header %}


{% block first_sidebar %}
  <li>
    <a href="{% url 'notification_hub:notifications' %}">
      All Notifications
    </a>
  </li>
  <li>
    <a class="selected" href="{% url 'notification_hub:unread' %}">
      Unread
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:read' %}">
      Read
    </a>
  </li>
  <li>
    <a href="{% url 'notification_hub:deletion_view' %}">
      Deletion View
    </a>
  </li>
{% endblock first_sidebar %}


{% block body_header %}
  <th>Unread Notifications</th>
  <th class="circle--cell--right">Time of notification</th>
{% endblock body_header %}


{% block body %}
  {% if not notification_query %}
    <h2>You are up to date on notifications!</h2>
  {% endif %}

  {% for notification in notification_query %}
    <tr class="clickable-row" data-href="">
      <td>
        <h3>
          <a>
            {{ notification.verb }}
          </a>
        </h3>
        <p>
          <a href={% url 'profiles:profile' pk=notification.actor.pk %}>
            From: {{ notification.actor }}
          </a>
        </p>

      </td>

      <td class="circle--cell--right">
              <span class="secondary-label">
                  {{ notification.timestamp }}
                  <a class="button button-primary extra_vertical_margin"
                     href= {% url 'notification_hub:mark_read' pk=notification.pk %}>
                    Mark read
                  </a>
              </span>
      </td>

    </tr>
  {% endfor %}
{% endblock body %}